from fpdf import FPDF
name = input("Name: ")
pdf = FPDF()
pdf.add_page()
pdf.set_font("helvetica", size = 48)
pdf.cell(0, 50, "CS50 Shirtificate", align="C")
pdf.image("shirtificate.png", x=15, y= 70, w=180)
pdf.set_font("helvetica", size=24)
pdf.set_text_color(255,255,255)
pdf.text(55, 140, f"{name} took CS50")
pdf.output("shirtificate.pdf")
